/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
const documents = {
    "\n  query cachedMessages($chatId: String!) {\n    cachedMessages(input: { chatId: $chatId }) {\n      edges {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      pageInfo {\n        endCursor\n        hasPreviousPage\n        hasNextPage\n      }\n      scrollPosition\n    }\n  }\n": types.CachedMessagesDocument,
    "\n  query messages($chatId: String!, $limit: Int, $after: ID) {\n    messages(input: { chatId: $chatId }, limit: $limit, after: $after) {\n      edges {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      pageInfo {\n        endCursor\n        hasPreviousPage\n        hasNextPage\n      }\n      scrollPosition\n    }\n  }\n": types.MessagesDocument,
    "\n  mutation createMessage(\n    $userId: String!\n    $chatId: String!\n    $queueId: String!\n    $isQueued: Boolean!\n    $queuedTimestamp: Float!\n    $isSent: Boolean!\n    $sentTimestamp: Float!\n    $message: String!\n  ) {\n    createMessage(\n      input: {\n        userId: $userId\n        chatId: $chatId\n        queueId: $queueId\n        isQueued: $isQueued\n        queuedTimestamp: $queuedTimestamp\n        isSent: $isSent\n        sentTimestamp: $sentTimestamp\n        message: $message\n      }\n    ) {\n      _id\n      queueId\n    }\n  }\n": types.CreateMessageDocument,
    "\n  subscription OnMessageAdded {\n    OnMessageAdded {\n      message {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n    }\n  }\n": types.OnMessageAddedDocument,
    "\n  subscription OnMessageUpdated {\n    OnMessageUpdated {\n      message {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n    }\n  }\n": types.OnMessageUpdatedDocument,
    "\n  query chat($chatId: String!) {\n    chat(input: { chatId: $chatId }) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      createdAt\n    }\n  }\n": types.ChatDocument,
    "\n  query chats($userId: String!, $limit: Int, $after: ID) {\n    chats(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      createdAt\n    }\n  }\n": types.ChatsDocument,
    "\n  mutation createChat(\n    $userId: String!\n    $queueId: String!\n    $type: String!\n    $friendIds: [String!]!\n    $friendUserIds: [String!]!\n  ) {\n    createChat(\n      input: {\n        userId: $userId\n        queueId: $queueId\n        type: $type\n        friendIds: $friendIds\n        friendUserIds: $friendUserIds\n      }\n    ) {\n      _id\n      queueId\n    }\n  }\n": types.CreateChatDocument,
    "\n  subscription OnChatAdded {\n    OnChatAdded {\n      friendIds\n      chat {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        createdAt\n      }\n    }\n  }\n": types.OnChatAddedDocument,
    "\n  subscription OnChatUpdated {\n    OnChatUpdated {\n      chat {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        createdAt\n      }\n    }\n  }\n": types.OnChatUpdatedDocument,
    "\n  query friend($friendId: String!, $userId: String!) {\n    friend(input: { friendId: $friendId, userId: $userId }) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n": types.FriendDocument,
    "\n  query friends($userId: String!, $limit: Int, $after: ID) {\n    friends(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n": types.FriendsDocument,
    "\n  query otherFriends($userId: String!, $limit: Int, $after: ID) {\n    otherFriends(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n": types.OtherFriendsDocument,
    "\n  subscription OnFriendAdded {\n    OnFriendAdded {\n      friend {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        hasChats\n        createdAt\n      }\n    }\n  }\n": types.OnFriendAddedDocument,
    "\n  query pendingRequests($userId: String!, $limit: Int, $after: ID) {\n    pendingRequests(input: { userId: $userId }, limit: $limit, after: $after) {\n      data {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n      totalCount\n    }\n  }\n": types.PendingRequestsDocument,
    "\n  query sentRequests($userId: String!, $limit: Int, $after: ID) {\n    sentRequests(input: { userId: $userId }, limit: $limit, after: $after) {\n      data {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n      totalCount\n    }\n  }\n": types.SentRequestsDocument,
    "\n  mutation createRequest($userId: String!, $sendToEmail: String!) {\n    createRequest(input: { userId: $userId, sendToEmail: $sendToEmail }) {\n      _id\n    }\n  }\n": types.CreateRequestDocument,
    "\n  mutation updateRequest(\n    $userId: String!\n    $requestId: String!\n    $status: String!\n  ) {\n    updateRequest(\n      input: { userId: $userId, requestId: $requestId, status: $status }\n    ) {\n      _id\n    }\n  }\n": types.UpdateRequestDocument,
    "\n  subscription OnRequestAdded {\n    OnRequestAdded {\n      request {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n    }\n  }\n": types.OnRequestAddedDocument,
    "\n  subscription OnRequestUpdated {\n    OnRequestUpdated {\n      request {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n    }\n  }\n": types.OnRequestUpdatedDocument,
    "\n  query userSessions($userId: String!) {\n    userSessions(input: { userId: $userId }) {\n      _id\n      userId\n      lastActive\n      deviceDetails\n      expires\n      lastActive\n    }\n  }\n": types.UserSessionsDocument,
    "\n  subscription OnSessionUpdated($sessionID: String!) {\n    OnSessionUpdated(input: { sessionID: $sessionID }) {\n      session {\n        _id\n        userId\n        lastActive\n        deviceDetails\n        expires\n        lastActive\n      }\n    }\n  }\n": types.OnSessionUpdatedDocument,
    "\n  query activeClients($userId: String!) {\n    activeClients(input: { userId: $userId }) {\n      userId\n      onlineStatus {\n        isOnline\n        lastSeen\n      }\n    }\n  }\n": types.ActiveClientsDocument,
    "\n  subscription OnClientsUpdated {\n    OnClientsUpdated {\n      userId\n      onlineStatus {\n        isOnline\n        lastSeen\n      }\n    }\n  }\n": types.OnClientsUpdatedDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query cachedMessages($chatId: String!) {\n    cachedMessages(input: { chatId: $chatId }) {\n      edges {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      pageInfo {\n        endCursor\n        hasPreviousPage\n        hasNextPage\n      }\n      scrollPosition\n    }\n  }\n"): (typeof documents)["\n  query cachedMessages($chatId: String!) {\n    cachedMessages(input: { chatId: $chatId }) {\n      edges {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      pageInfo {\n        endCursor\n        hasPreviousPage\n        hasNextPage\n      }\n      scrollPosition\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query messages($chatId: String!, $limit: Int, $after: ID) {\n    messages(input: { chatId: $chatId }, limit: $limit, after: $after) {\n      edges {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      pageInfo {\n        endCursor\n        hasPreviousPage\n        hasNextPage\n      }\n      scrollPosition\n    }\n  }\n"): (typeof documents)["\n  query messages($chatId: String!, $limit: Int, $after: ID) {\n    messages(input: { chatId: $chatId }, limit: $limit, after: $after) {\n      edges {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      pageInfo {\n        endCursor\n        hasPreviousPage\n        hasNextPage\n      }\n      scrollPosition\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation createMessage(\n    $userId: String!\n    $chatId: String!\n    $queueId: String!\n    $isQueued: Boolean!\n    $queuedTimestamp: Float!\n    $isSent: Boolean!\n    $sentTimestamp: Float!\n    $message: String!\n  ) {\n    createMessage(\n      input: {\n        userId: $userId\n        chatId: $chatId\n        queueId: $queueId\n        isQueued: $isQueued\n        queuedTimestamp: $queuedTimestamp\n        isSent: $isSent\n        sentTimestamp: $sentTimestamp\n        message: $message\n      }\n    ) {\n      _id\n      queueId\n    }\n  }\n"): (typeof documents)["\n  mutation createMessage(\n    $userId: String!\n    $chatId: String!\n    $queueId: String!\n    $isQueued: Boolean!\n    $queuedTimestamp: Float!\n    $isSent: Boolean!\n    $sentTimestamp: Float!\n    $message: String!\n  ) {\n    createMessage(\n      input: {\n        userId: $userId\n        chatId: $chatId\n        queueId: $queueId\n        isQueued: $isQueued\n        queuedTimestamp: $queuedTimestamp\n        isSent: $isSent\n        sentTimestamp: $sentTimestamp\n        message: $message\n      }\n    ) {\n      _id\n      queueId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnMessageAdded {\n    OnMessageAdded {\n      message {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnMessageAdded {\n    OnMessageAdded {\n      message {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnMessageUpdated {\n    OnMessageUpdated {\n      message {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnMessageUpdated {\n    OnMessageUpdated {\n      message {\n        _id\n        chatId\n        queueId\n        message\n        sender {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query chat($chatId: String!) {\n    chat(input: { chatId: $chatId }) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query chat($chatId: String!) {\n    chat(input: { chatId: $chatId }) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query chats($userId: String!, $limit: Int, $after: ID) {\n    chats(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query chats($userId: String!, $limit: Int, $after: ID) {\n    chats(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation createChat(\n    $userId: String!\n    $queueId: String!\n    $type: String!\n    $friendIds: [String!]!\n    $friendUserIds: [String!]!\n  ) {\n    createChat(\n      input: {\n        userId: $userId\n        queueId: $queueId\n        type: $type\n        friendIds: $friendIds\n        friendUserIds: $friendUserIds\n      }\n    ) {\n      _id\n      queueId\n    }\n  }\n"): (typeof documents)["\n  mutation createChat(\n    $userId: String!\n    $queueId: String!\n    $type: String!\n    $friendIds: [String!]!\n    $friendUserIds: [String!]!\n  ) {\n    createChat(\n      input: {\n        userId: $userId\n        queueId: $queueId\n        type: $type\n        friendIds: $friendIds\n        friendUserIds: $friendUserIds\n      }\n    ) {\n      _id\n      queueId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnChatAdded {\n    OnChatAdded {\n      friendIds\n      chat {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        createdAt\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnChatAdded {\n    OnChatAdded {\n      friendIds\n      chat {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        createdAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnChatUpdated {\n    OnChatUpdated {\n      chat {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        createdAt\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnChatUpdated {\n    OnChatUpdated {\n      chat {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        createdAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query friend($friendId: String!, $userId: String!) {\n    friend(input: { friendId: $friendId, userId: $userId }) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query friend($friendId: String!, $userId: String!) {\n    friend(input: { friendId: $friendId, userId: $userId }) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query friends($userId: String!, $limit: Int, $after: ID) {\n    friends(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query friends($userId: String!, $limit: Int, $after: ID) {\n    friends(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query otherFriends($userId: String!, $limit: Int, $after: ID) {\n    otherFriends(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query otherFriends($userId: String!, $limit: Int, $after: ID) {\n    otherFriends(input: { userId: $userId }, limit: $limit, after: $after) {\n      _id\n      queueId\n      type\n      members {\n        _id\n        hasAdded\n        name\n        picture\n        email\n        email_verified\n        given_name\n        family_name\n      }\n      lastMessage {\n        message\n        sender {\n          _id\n          retryStatus {\n            isRetry\n            timestamp\n          }\n          queuedStatus {\n            isQueued\n            timestamp\n          }\n          sentStatus {\n            isSent\n            timestamp\n          }\n        }\n        otherMembers {\n          _id\n          deliveredStatus {\n            isDelivered\n            timestamp\n          }\n          readStatus {\n            isRead\n            timestamp\n          }\n        }\n        timestamp\n      }\n      hasChats\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnFriendAdded {\n    OnFriendAdded {\n      friend {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        hasChats\n        createdAt\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnFriendAdded {\n    OnFriendAdded {\n      friend {\n        _id\n        queueId\n        type\n        members {\n          _id\n          hasAdded\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n        lastMessage {\n          message\n          sender {\n            _id\n            retryStatus {\n              isRetry\n              timestamp\n            }\n            queuedStatus {\n              isQueued\n              timestamp\n            }\n            sentStatus {\n              isSent\n              timestamp\n            }\n          }\n          otherMembers {\n            _id\n            deliveredStatus {\n              isDelivered\n              timestamp\n            }\n            readStatus {\n              isRead\n              timestamp\n            }\n          }\n          timestamp\n        }\n        hasChats\n        createdAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query pendingRequests($userId: String!, $limit: Int, $after: ID) {\n    pendingRequests(input: { userId: $userId }, limit: $limit, after: $after) {\n      data {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n      totalCount\n    }\n  }\n"): (typeof documents)["\n  query pendingRequests($userId: String!, $limit: Int, $after: ID) {\n    pendingRequests(input: { userId: $userId }, limit: $limit, after: $after) {\n      data {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n      totalCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query sentRequests($userId: String!, $limit: Int, $after: ID) {\n    sentRequests(input: { userId: $userId }, limit: $limit, after: $after) {\n      data {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n      totalCount\n    }\n  }\n"): (typeof documents)["\n  query sentRequests($userId: String!, $limit: Int, $after: ID) {\n    sentRequests(input: { userId: $userId }, limit: $limit, after: $after) {\n      data {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n      totalCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation createRequest($userId: String!, $sendToEmail: String!) {\n    createRequest(input: { userId: $userId, sendToEmail: $sendToEmail }) {\n      _id\n    }\n  }\n"): (typeof documents)["\n  mutation createRequest($userId: String!, $sendToEmail: String!) {\n    createRequest(input: { userId: $userId, sendToEmail: $sendToEmail }) {\n      _id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation updateRequest(\n    $userId: String!\n    $requestId: String!\n    $status: String!\n  ) {\n    updateRequest(\n      input: { userId: $userId, requestId: $requestId, status: $status }\n    ) {\n      _id\n    }\n  }\n"): (typeof documents)["\n  mutation updateRequest(\n    $userId: String!\n    $requestId: String!\n    $status: String!\n  ) {\n    updateRequest(\n      input: { userId: $userId, requestId: $requestId, status: $status }\n    ) {\n      _id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnRequestAdded {\n    OnRequestAdded {\n      request {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnRequestAdded {\n    OnRequestAdded {\n      request {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnRequestUpdated {\n    OnRequestUpdated {\n      request {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnRequestUpdated {\n    OnRequestUpdated {\n      request {\n        _id\n        members {\n          _id\n          hasSent\n          name\n          picture\n          email\n          email_verified\n          given_name\n          family_name\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query userSessions($userId: String!) {\n    userSessions(input: { userId: $userId }) {\n      _id\n      userId\n      lastActive\n      deviceDetails\n      expires\n      lastActive\n    }\n  }\n"): (typeof documents)["\n  query userSessions($userId: String!) {\n    userSessions(input: { userId: $userId }) {\n      _id\n      userId\n      lastActive\n      deviceDetails\n      expires\n      lastActive\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnSessionUpdated($sessionID: String!) {\n    OnSessionUpdated(input: { sessionID: $sessionID }) {\n      session {\n        _id\n        userId\n        lastActive\n        deviceDetails\n        expires\n        lastActive\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnSessionUpdated($sessionID: String!) {\n    OnSessionUpdated(input: { sessionID: $sessionID }) {\n      session {\n        _id\n        userId\n        lastActive\n        deviceDetails\n        expires\n        lastActive\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query activeClients($userId: String!) {\n    activeClients(input: { userId: $userId }) {\n      userId\n      onlineStatus {\n        isOnline\n        lastSeen\n      }\n    }\n  }\n"): (typeof documents)["\n  query activeClients($userId: String!) {\n    activeClients(input: { userId: $userId }) {\n      userId\n      onlineStatus {\n        isOnline\n        lastSeen\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription OnClientsUpdated {\n    OnClientsUpdated {\n      userId\n      onlineStatus {\n        isOnline\n        lastSeen\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription OnClientsUpdated {\n    OnClientsUpdated {\n      userId\n      onlineStatus {\n        isOnline\n        lastSeen\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;